apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ghcfbr23o-nodejs
  janus-idp.io/tekton: ghcfbr23o-nodejs
  backstage.io/kubernetes-id: ghcfbr23o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ghcfbr23o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
